# -*- coding: utf-8 -*-
# all available properties in serverless.yml when provider is aws
# https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/

service:
  name: dupe-remove-demo

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-west-2
  profile: identitysandbox.gov
  memorySize: 128
  timeout: 30
  deploymentBucket:
    name: login.gov-dev-sanhe
  deploymentPrefix: serverless
  role: arn:aws:iam::894947205914:role/lambda-s3-redshift-full-access
  versionFunctions: false

package:
  artifact: ./build/lambda/source.zip

functions:
  postgres:
    handler: dupe_remove.handlers.postgres.handler
    layers:
      - arn:aws:lambda:us-west-2:894947205914:layer:dupe_remove:2

  redshift:
    handler: dupe_remove.handlers.redshift.handler
    layers:
      - arn:aws:lambda:us-west-2:894947205914:layer:dupe_remove:2
