# -*- coding: utf-8 -*-
# all available properties in serverless.yml when provider is aws
# https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/

service:
  name: dupe-remove-demo

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-west-2
  profile: identitysandbox.gov
  memorySize: 128
  timeout: 60
  deploymentBucket:
    name: login.gov-dev-sanhe
  deploymentPrefix: serverless
  role: arn:aws:iam::894947205914:role/lambda-s3-redshift-full-access
  versionFunctions: false

package:
  artifact: ./build/lambda/source.zip

functions:
  sanhehu_elephant_db_t_events:
    handler: dupe_remove.handlers.sanhehu_elephant_db_t_events.handler
    description:
    layers:
      - arn:aws:lambda:us-west-2:894947205914:layer:dupe_remove:1

  identity_analytics_dev_redshift:
    handler: dupe_remove.handlers.identity_analytics_dev_redshift.handler
    timeout: 300
    layers:
      - arn:aws:lambda:us-west-2:894947205914:layer:dupe_remove:1
